[platformio]
default_envs = bench

[env]
platform = espressif32
board = telloesp32
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.f_cpu = 160000000L
board_build.f_flash = 40000000L
board_build.flash_mode = dio
board_build.partitions = partitions/minimal.csv
lib_deps = pololu/VL53L0X

[env:bench]
build_flags = -D TOF_LIVE=0

[env:live]
build_flags = -D TOF_LIVE=1
